[project]
name = "social-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-fasthtml>=0.6.0",
    "redis>=5.0.8",
]

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.3",
]
